kind: Service
apiVersion: v1
metadata:
  name: test-jenkins
  namespace : streams
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Deployment
      name:  test-jenkins
      prefix: /testjenkins/
      service: test-jenkins.streams:2127
      rewrite: /enkintestjenkins/
spec:
  type: NodePort
  selector:
    app: test-jenkins
  ports:
  - protocol: TCP
    name : proto1
    port: 2128

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-jenkins
  namespace : streams
  labels: 
      keel.sh/policy: force
      keel.sh/approvals: "1"
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: test-jenkins
    spec:
      containers:
      - name: test-jenkins
        image: docker.io/abhishek1691/production-server:latest
        ports:
        - containerPort: 2128
