kind: Service
apiVersion: v1
metadata:
  name: dahboard-manager
  namespace : streams
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  dashboard-manager
      prefix: /dashboard/
      service: dashboard-manager.streams:2127
      rewrite: /dashboard/
spec:
  type: NodePort
  selector:
    app: dahboard-manager
  ports:
  - protocol: TCP
    name : proto1
    port: 2127

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dahboard-manager
  namespace : streams
  labels:
      keel.sh/policy: force
      keel.sh/approvals: "1"
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: dahboard-manager
    spec:
      containers:
      - name: dahboard-manager
        image: gcr.io/fretron-server/dashboard-manager-test:latest
        ports:
        - containerPort: 2127
