apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fretron-jenkins
  labels:
      keel.sh/policy: force
      keel.sh/approvals: "1"
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: fretron-jenkins
    spec:
      containers:
      - name: fretron-jenkins
        image: abhishek1691/test@sha256:54a81b35c9d62f87fce2330df9db5b00e24d03f91caea371a91cf1f5fc5857db
---
kind: Service
apiVersion: v1
metadata:
  name: fretron-jenkins
spec:
  type: NodePort
  selector:
    app: fretron-jenkins
  ports:
  - protocol: TCP
    name : proto1
    port: 5555
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fretron-jenkins
spec:
  rules:
  - host: mytesthost.com
    http:
      paths:
      - path: /test
        backend:
          serviceName: fretron-jenkins
          servicePort: 5555
